import { Geist } from "next/font/google";
import "./globals.css";
import NavBar from "./component/NavBar";
import WorkoutProvider from "./context/WorkoutContext";
import Fooder from "./component/Fooder";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WorkoutProvider>
          <NavBar />
          {children}
          <Fooder />
        </WorkoutProvider>
      </body>
    </html>
  );
}