import { Geist } from "next/font/google";
import "./globals.css";
import NavBar from "./component/NavBar";
import WorkoutProvider from "./context/WorkoutContext";
import Fooder from "./component/Fooder";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">

        <WorkoutProvider>

          <NavBar />

          <main className="flex-1">
            {children}
          </main>

          <Fooder />
            <ToastContainer />

        </WorkoutProvider>

      </body>
    </html>
  );
}